import Head from 'next/head'
// import Image from 'next/image'
import Script from 'next/script'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      {/* Note - to use styled jsx, you need to add  styled-jsx package*/}
      <style jsx>
        {
          `
            .blogTitle{
              font-size: 2.rem;
            }
            .blogItem h3{
              font-size: 1.5rem;
            }
            .blogItem p{
              font-size: 1rem;
            }
          `
        }
      </style>
      <Head>
        <title>Codewalker Saga</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, nextblog, codewalker saga"/>
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      
      {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          The CodeWalker Blog
        </h1>
          <div className={styles.imgWrap}>
            {/* <Image className={styles.mainImg} src='/home.jpg' width={400} height={250}/> */}
            <img className={styles.mainImg} src='/home.jpg' alt='Mihawk Blog'></img>
          </div>

        <p className={styles.description}>This is the Codewalker Blog</p>
        
        <div className="blogs">
          <h2 className='blogTitle'>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022?</h3>
            <p>Javascript is the premier language used for web development.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022?</h3>
            <p>Javascript is the premier language used for web development.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022?</h3>
            <p>Javascript is the premier language used for web development.</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
