import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Codewalker Saga</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, nextblog, codewalker saga"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*This is the navigation bar component */}
      <nav className={styles.mainnav}>
        <ul>
          <Link href='/'><a><li>Home</li></a></Link>
          <Link href='/about'><a><li>About</li></a></Link>
          <Link href='/contact'><a><li href='/'>Contact</li></a></Link>
          <Link href='/blog'><a><li>Blog</li></a></Link>
        </ul>
      </nav>
      {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          The CodeWalker Blog
        </h1>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022?</h3>
            <p>Javascript is the premier language used for web development.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022?</h3>
            <p>Javascript is the premier language used for web development.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022?</h3>
            <p>Javascript is the premier language used for web development.</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
