import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      {/* Note - to use styled jsx, you need to add  styled-jsx package*/}
      <style jsx>
        {
          `
            .blogTitle{
              font-size: 2.25rem;
            }
            .blogItem h3{
              font-size: 1.5rem;
            }
            .blogItem p{
              font-size: 1rem;
            }
          `
        }
      </style>
      <Head>
        <title>Codewalker Saga</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, nextblog, codewalker saga"/>
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      {/*This is the navigation bar component */}
      <nav className={styles.mainnav}>
        <ul>
          <Link href='/'><a><li>Home</li></a></Link>
          <Link href='/about'><a><li>About</li></a></Link>
          <Link href='/contact'><a><li href='/'>Contact</li></a></Link>
          <Link href='/blog'><a><li>Blog</li></a></Link>
        </ul>
      </nav>
      {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          The CodeWalker Blog
          <span className='mySpan'>Episode IV</span>
        </h1>
          <div className={styles.imgWrap}>
            <Image className={styles.mainImg} src='/home.jpg' width={400} height={250}/>
          </div>

        <p className={styles.description}>This is the Codewalker Blog</p>
        
        <div className="blogs">
          <h2 className='blogTitle'>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022?</h3>
            <p>Javascript is the premier language used for web development.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022?</h3>
            <p>Javascript is the premier language used for web development.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2022?</h3>
            <p>Javascript is the premier language used for web development.</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
